# Generated by Django 3.2.9 on 2021-11-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name_consultory',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
