# Generated by Django 3.2.9 on 2021-11-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_client_name_consultory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
