# Generated by Django 3.2.9 on 2021-11-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20211113_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotafacture',
            name='iva',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotafacture',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factureline',
            name='interest',
            field=models.IntegerField(null=True),
        ),
    ]
