# Generated by Django 3.2.9 on 2021-11-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20211113_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureline',
            name='total_payment',
            field=models.IntegerField(null=True),
        ),
    ]
