# Generated by Django 3.2.9 on 2021-11-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_alter_product_code'),
        ('factura', '0007_alter_factureline_total_payment'),
    ]

    operations = [
    ]
