# Generated by Django 3.2.9 on 2021-11-23 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_merge_20211114_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureline',
            name='product',
        ),
        migrations.AlterField(
            model_name='factureline',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factureline',
            name='total_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('num_products', models.IntegerField(default=1)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factureline')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.product')),
            ],
            options={
                'verbose_name': 'Productos Factura',
                'verbose_name_plural': 'Productos Facturas',
                'db_table': 'products_facture',
            },
        ),
        migrations.AddField(
            model_name='factureline',
            name='products',
            field=models.ManyToManyField(blank=True, through='factura.ProductFacture', to='factura.Product'),
        ),
    ]
