# Generated by Django 3.2.9 on 2021-11-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_auto_20211122_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productfacture',
            unique_together={('product', 'facture')},
        ),
    ]
