# Generated by Django 3.2.9 on 2021-11-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0010_alter_productfacture_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotafacture',
            name='iva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotafacture',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
