# Generated by Django 3.2.9 on 2021-11-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0011_auto_20211122_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureline',
            name='products',
        ),
        migrations.DeleteModel(
            name='ProductFacture',
        ),
    ]
