# Generated by Django 3.2.9 on 2021-11-26 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0012_auto_20211125_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('num_products', models.IntegerField(default=1)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factureline')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.product')),
            ],
            options={
                'verbose_name': 'Productos Factura',
                'verbose_name_plural': 'Productos Facturas',
                'db_table': 'products_facture',
            },
        ),
    ]
