# Generated by Django 3.2.9 on 2021-11-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0013_productsfacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureline',
            name='value_quote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
