# Generated by Django 3.2.9 on 2021-11-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0014_factureline_value_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureline',
            name='doc_patient',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='factureline',
            name='fullname_patient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
