# Generated by Django 3.2.9 on 2021-12-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0015_auto_20211126_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureline',
            name='n_invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
