# Generated by Django 3.2.9 on 2021-12-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0016_factureline_n_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureline',
            name='n_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
