# Generated by Django 3.2.9 on 2021-12-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0017_alter_factureline_n_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsfacture',
            name='total_value',
            field=models.IntegerField(null=True),
        ),
    ]
