# Generated by Django 3.2.9 on 2021-12-07 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0018_productsfacture_total_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('type_payment', models.CharField(max_length=10)),
                ('total_payment', models.IntegerField()),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factureline')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
