# Generated by Django 3.2.9 on 2021-12-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0019_paymentsfacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsfacture',
            name='type_payment',
            field=models.CharField(choices=[('TC', 'Tarjeta de Credito'), ('EF', 'Efectivo'), ('TR', 'Transferencia')], max_length=10),
        ),
    ]
