# Generated by Django 3.2.9 on 2021-12-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0021_paymentsfacture_n_consecutive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsfacture',
            name='n_consecutive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
