# Generated by Django 3.2.9 on 2021-12-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0022_alter_paymentsfacture_n_consecutive'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureline',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
